Fix market hour pages headings
QuantConnect/Documentation pull request #1206
Opened 2023-03-30 09:16 UTC by LouisSzeto

#### Description
Correction in CFD/Futures generated pages' heading from "Market Opening Hours" -> "Regular Trading Hours"

#### Related Issue
closes #1200

#### Motivation and Context
Consistency

#### Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [X] My code follows the code style of this project.
- [X] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [X] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

2023-03-30 16:25 UTC, DerekMelchin requested changes

2023-03-30 16:25 UTC, DerekMelchin commented on Resources/datasets/market-hours/equity/india/generic/regular-trading-hours.html
If you rename this file, you also need to adjust the `include` statement in `Documentation\03 Writing Algorithms\03 Securities\99 Asset Classes\02 India Equity\05 Market Hours\03 Regular Trading Hours.php`

2023-03-30 16:25 UTC, DerekMelchin commented on Resources/datasets/market-hours/equity/usa/generic/regular-trading-hours.html
If you rename this file, you also need to adjust the `include` statement in `Documentation\03 Writing Algorithms\03 Securities\99 Asset Classes\01 US Equity\09 Market Hours\03 Regular Trading Hours.php`

2023-03-30 16:25 UTC, DerekMelchin commented on Resources/datasets/market-hours/index/usa/generic/regular-trading-hours.html
If you rename this file, you also need to adjust the `include` statement in `Documentation\03 Writing Algorithms\03 Securities\99 Asset Classes\09 Index\04 Market Hours\03 Regular Trading Hours.php`

2023-03-30 16:25 UTC, DerekMelchin commented on Resources/datasets/market-hours/option/usa/generic/regular-trading-hours.html
If you rename this file, you also need to adjust the `include` statement in `Documentation\03 Writing Algorithms\03 Securities\99 Asset Classes\03 Equity Options\04 Market Hours\03 Regular Trading Hours.php`

2023-03-30 18:32 UTC, AlexCatarino requested changes
We should review the possible improvement of this code generation. It seems odd that we have a market-hour-convertor and a market-hour-code-generator. Why the convertor is not part of the generator? We had to replace "market-opening-hours.html" with "regular-trading-hours.html" which shows that these scripts are error-prone.

I have created the `_code_generation_helpers.py` to avoid code duplication. We can use it to define global variables.

2023-03-31 05:50 UTC, LouisSzeto commented
> We should review the possible improvement of this code generation. It seems odd that we have a market-hour-convertor and a market-hour-code-generator. Why the convertor is not part of the generator?

This is mainly due to the workflow of `source -> RESOURCES -> production page`, so we separated 2 files here.

2023-03-31 12:15 UTC, merged