Update description in docs
QuantConnect/Documentation pull request #1661
Opened 2024-03-28 14:47 UTC by Marinovsky

#### Description

- Add missing descriptions for some objects
- Update certain objects since new changes will be done in the API (see https://github.com/QuantConnect/Lean/issues/7835)
#### Related Issue

N/A
#### Motivation and Context

API docs wasn't updated
#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

2024-04-09 13:57 UTC, Martin-Molinero approved these changes
Nice!

2024-04-09 14:50 UTC, AlexCatarino requested changes
Thank you, @Marinovsky .

I think we should take the opportunity to review other issues. For example, `files/update` is using:

```xml
    UpdateFileNameRequest:
      type: object
      properties:
        projectId:
          type: integer
          description: Project Id to which the file belongs.
        oldFileName:
          type: string
          description: The current name of the new file.
        newFileName:
          type: string
          description: The new name for the file.
      description: Request to update the name of a file.
```

which is incorrect. It is `name`, `content` to update the content; and `name`, `newName` to rename the file.

2024-04-10 13:53 UTC, Martin-Molinero approved these changes

2024-04-10 14:26 UTC, AlexCatarino approved these changes

2024-04-10 14:27 UTC, merged